- helm_deploy/hmpps-incentives-api/values.yaml
Reverts ministryofjustice/hmpps-incentives-api#13
> Revert "INC-127 Increase timeout on NGINX"

- README.md
- doc/architecture/decisions/0001-use-adr.md
- doc/architecture/decisions/0002-incentive-api-architecture.md
- doc/architecture/decisions/9999-end.md
> INC-179 Record architecture decisions.

- helm_deploy/values-dev.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveSummaryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonApiDto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonApiService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/PrisonApiMockServer.kt
> INC-220 Improve performance of review table

- .circleci/config.yml
- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-293
Raised after discussion - https://github.com/ministryofjustice/digital-prison-services/pull/2081/files#r839517993
> INC-293: add with-details flag to getPrisonerIepLevelHistory

- docker-compose.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-293
> INC-293: use same Prison API endpoint which DPS used to call

- .github/CODEOWNERS
- .trivyignore
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- helm_deploy/hmpps-incentives-api/Chart.yaml
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/OpenApiDocsTest.kt
https://dsdmoj.atlassian.net/browse/INC-483
> INC-483: add codeowners; bump dependencies

- README.md
https://dsdmoj.atlassian.net/browse/INC-483
Operations Engineering create a [daily report](https://operations-engineering-reports.cloud-platform.service.justice.gov.uk/github_repositories) which scans repos for compliance with their standards and saw them add a badge to each project - see https://github.com/ministryofjustice/github-repository-standards/pull/22
> INC-483: add the moj compliant badge to the readme

- build.gradle.kts
https://dsdmoj.atlassian.net/browse/INC-493
> INC-493: bump dependencies

- .circleci/config.yml
- build.gradle.kts
https://dsdmoj.atlassian.net/browse/INC-545
> INC-545: bump gradle dependencies

- .circleci/config.yml
https://dsdmoj.atlassian.net/browse/INC-545
Reverts changes in https://github.com/ministryofjustice/hmpps-incentives-api/pull/67
> INC-545: fixes so security pipeline works with Orb v5 

- src/main/resources/db/migration/V1_10__iep_prisons_eh3.sql
- src/main/resources/db/migration/V1_9__iep_prisons_en3.sql
> INC-609 Add Enhanced 2 and 3 to Portland Prison

- build.gradle.kts
- postgres-suppressions.xml
- src/main/resources/application.yml
> INC-615  Fix Incentives API database connection issues

- Dockerfile
Cherry picked from https://github.com/ministryofjustice/hmpps-template-kotlin/pull/98
> Cherry pick change from hmpps-template-kotlin

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-434
> INC-434: change review logic to be the same as admission; add integration test

- helm_deploy/hmpps-incentives-api/values.yaml
…retaining the old one so that traffic slowly migrates to the new one.
C.f. https://github.com/ministryofjustice/hmpps-helm-charts/releases/tag/generic-service-1.5.0
> INC-668: Create new ingress

- helm_deploy/hmpps-incentives-api/values.yaml
C.f. https://github.com/ministryofjustice/hmpps-helm-charts/releases/tag/generic-service-1.5.0
> INC-668: Complete upgrade of ingresses by removing the old one

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/HmppsIncentivesApiExceptionHandler.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
https://dsdmoj.atlassian.net/browse/INC-566
> INC-566: return HTTP status 400 if it receives undefined parameter

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonApiService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/PrisonApiMockServer.kt
https://dsdmoj.atlassian.net/browse/INC-697
> INC-697: pass includeInactive=true to prison-api getLocation

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IepLevelServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-672
> INC-672: Implement the transfer policy logic

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IepSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-722
> INC-722: add migrateIepReview endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/AuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-736
> INC-736: raise IEP domain event for transfer and first arrival

- src/main/resources/application-localstack.yml
- src/main/resources/application.yml
- src/test/resources/application-test.yml
https://dsdmoj.atlassian.net/browse/INC-768
> INC-768: use asynchronous SQS library queue-admin endpoints and override default role

- helm_deploy/hmpps-incentives-api/values.yaml
https://dsdmoj.atlassian.net/browse/INC-768
> INC-768: fix helm DLQ param name

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IepSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/PrisonerIepLevel.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/main/resources/db/migration/V1_12__prisoner_iep_nullable_reviewed_by.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-769
> INC-769: handle null userId when migrating record from NOMIS

- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
GitHub didn't spot the problem and it didn't compile.
> Fix new test still using `sequence` column (now dropped)

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/PrisonerIepLevel.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-784
> INC-784: add MIGRATED review type

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-822
> INC-822: use client credentials when making calls to PrisonAPI during sync and migration flows

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IepSummary.kt
https://dsdmoj.atlassian.net/browse/INC-826
> INC-826: make SyncPostRequest.comment nullable

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IepSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/PrisonerIepLevel.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/main/resources/db/migration/V1_13__prisoner_iep_nullable_location_id.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-831
> INC-831: drop SyncPostRequest.locationId and make it nullable

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonerIepLevelRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
> INC-446 Handle Prisoner number merge

- .circleci/config.yml
https://dsdmoj.atlassian.net/browse/INC-634
> INC-634: re-enable Veracode pipeline scan

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonerIepLevelRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/main/resources/db/migration/V1_14__prisoner_iep_current_true_constraint.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonerIepLevelRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-823
> INC-823: when SyncPostRequest.current or SyncPatchRequest.current is true then update IEP level with current flag to false

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IepLevelService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IepLevelServiceTest.kt
> INC-876 Don't use iep level table

- README.md
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IncentiveReview.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/OffenderSearch.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/health/OffenderSearchApiHealthCheck.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/OffenderSearchService.kt
- src/main/resources/application-dev.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/health/HealthCheckTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/OffenderSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/OffenderSearchServiceTest.kt
- src/test/resources/application-test.yml
…which will be iteratively enhanced to show information relevant to incentive reviews in future.
> INC-846 & INC-842: Return basic information about prisoners in a given location

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/OffenderSearch.kt
Addresses https://github.com/ministryofjustice/hmpps-incentives-api/pull/216#discussion_r1005467608
> Use more idiomatic code style

- helm_deploy/values-dev.yaml
> INC-887 Master incentives data from Incentives Service (DB) - Dev (T3)

- helm_deploy/values-preprod.yaml
> INC-889 Switch to using incentive database for pre-prod and fire domain events for changes.

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IncentiveReview.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-840
https://dsdmoj.atlassian.net/browse/INC-841
> INC-840 & INC-841: add Behaviour Entries in the Last 3 Months to IncentiveReviewResponse

- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IepSummaryDateTest.kt
…making them easier to read now that the "now" time is fixed
> INC-890: Hard-code dates within incentive level date calculation tests

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/HmppsIncentivesApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IncentiveReview.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-848
> INC-848: include simplest calculation for date of next review

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IncentiveReview.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsServiceTest.kt
https://dsdmoj.atlassian.net/browse/INC-838
> INC-838: total of Overdue Prisoner Review

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/OffenderSearchService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/OffenderSearchMockServer.kt
> INC-900 Fix API call

- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/main/resources/application-localstack.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
- src/test/resources/application-test.yml
- src/test/resources/messages/prisonerReceivedReasonAdmission.json
- src/test/resources/messages/prisonerReceivedReasonTransferred.json
https://dsdmoj.atlassian.net/browse/INC-766
> INC-766: use "more prompt" domain events; update admission reason values which have now been split out

- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonOffenderEventListener.kt
- src/main/resources/application-localstack.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
- src/test/resources/application-test.yml
- src/test/resources/messages/prisonerReceivedReasonAdmission.json
- src/test/resources/messages/prisonerReceivedReasonTransferred.json
https://dsdmoj.atlassian.net/browse/INC-766
> INC-766: event name prefix should be prisoner instead of prison

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/OffenderSearch.kt
https://dsdmoj.atlassian.net/browse/INC-923
> INC-923: make cellLocation nullable

- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsServiceTest.kt
…by ensuring that pagination and by-level filtering do not affect it – i.e. that all levels and pages are considered
> INC-898: Increase test coverage of overdue count in incentive reviews response

- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
The test seems to fail quite frequently, example:
https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-incentives-api/1152/workflows/a3fb2a68-8fe0-417d-bdb6-10a933ab2c88/jobs/3838
The tests tend to fail when waiting for the request to Prison API in an attempt to determine whether the admission domain event(s) have been processed.
Maybe these tests starting to early causing the 30s timeout to lapse.
I've added another condition to check a review record has been created before those prisonApi mock requests are checked: An admission creates a review record so check for new records should be a good indication the event may have been processed (or at least almost).
I'm not 100% sure this will fix this test as it's still odd that 30s is not enough for this event to be processed.
> Attempt to fix flaky integration test

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
…on admission, readmission and transfer (irrespective of whether the level was not identical before)
> INC-871: Use simpler & clearer reasons for posting automated incentive reviews

- .circleci/config.yml
- docker-compose-local.yml
- docker-compose.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/LocalStackContainer.kt
There's also a [CircleCI orb for using localstack](https://docs.localstack.cloud/ci/circle-ci/) but that might be harder to use.
> INC-940: Investigate flakey tests

- .trivyignore
https://dsdmoj.atlassian.net/browse/INC-969
> INC-969: trivy ignore from DPS spring boot plugin

- src/main/resources/db/migration/V1_24__reviewed_by_incentives_api.sql
Fixes data saved prior to changes in #283
> INC-915: Rename historical `incentives-api` username in incentive level records

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonerIepLevelRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IepLevelService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
> INC-1001 Update only the current field for current incentives rather than whole record.

- renovate.json
https://dsdmoj.atlassian.net/browse/INC-1039
> INC-1039: source Renovate config from shared HMPPS repo

- helm_deploy/hmpps-incentives-api/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/resources/application-dev.yml
Also:
- Add queue alerting
- Remove unused feature switch
> INC-1011 Synchronise incentives prod database to preprod

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/OpenApiConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveSummaryResource.kt
> INC-1011 Swagger API Tidy up

- helm_deploy/values-dev.yaml
> INC-1119: use new HMPPS Domain Events queue from the Incentives namespace - DEV

- helm_deploy/values-dev.yaml
> INC-1119: second attempt

- helm_deploy/hmpps-incentives-api/values.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
> INC-1119: third attempt

- helm_deploy/values-dev.yaml
> INC-1119: update dev sqsAlertsQueueNames to use new queues

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/OpenApiConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/PrisonIncentiveLevelResource.kt
…in particular noting that new incentive levels apis are not yet enabled
> Improve resource documentation

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/ClientTrackingWebFilter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/SnsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/ClientTrackingWebFilterTest.kt
https://dsdmoj.atlassian.net/browse/INC-1198
> INC-1198: use Span annotations to log requests to AppInsights

- scripts/next-review-dates-by-prison.py
…because the service is now live in all prisons
> INC-1261: Make filtering for private beta prisons optional when compiling overdue review statistics

- helm_deploy/hmpps-incentives-api/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
https://dsdmoj.atlassian.net/browse/INC-1263
> INC-1263: use IRSA to connect to SQS and SNS - dev

- helm_deploy/hmpps-incentives-api/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
https://dsdmoj.atlassian.net/browse/INC-1263
Follows on from https://github.com/ministryofjustice/hmpps-incentives-api/pull/448
> INC-1263: use IRSA to connect to SQS and SNS - prod

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/CountPrisonersService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/CountPrisonersServiceTest.kt
…where offender search found no booking ids. The sql query was invalid `… WHERE booking_id IN ()`
> INC-1266: Fix counting prisoners on a level in a prison

- helm_deploy/hmpps-incentives-api/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
https://dsdmoj.atlassian.net/browse/HEAT-74
> HEAT-74: update to use new service account from latest irsa terraform module

- helm_deploy/hmpps-incentives-api/values.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/health/ProductIdInfoContributor.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsService.kt
Cherry-picked from [hmpps-template-kotlin#172](https://github.com/ministryofjustice/hmpps-template-kotlin/pull/172)
> Expose product ID

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/health/ProductIdInfoContributor.kt
…which was in the wrong package and not discovered/auto-loaded
Ref #483
> Fix product ID info component

- build.gradle.kts
- buildSrc/build.gradle.kts
…copied from [template#177](https://github.com/ministryofjustice/hmpps-template-kotlin/pull/177)
> Use tidier config for java language version

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonApiService.kt
call prison-api case notes with client token
> SDIT-1174 prison-api CaseNoteResource

- Dockerfile
…which now mostly matches [template](https://github.com/ministryofjustice/hmpps-template-kotlin/blob/61d0e0eab8523f0ae72e9f3850e74b8cbc8dfbd0/Dockerfile). #529 still included alpine-specific `RUN` statements.
> Fix Dockerfile’s migration from alpine to jammy

- applicationinsights.dev.json
- applicationinsights.json
Taken from upstream [hmpps-template-typescript#204](https://github.com/ministryofjustice/hmpps-template-kotlin/pull/204/files?w=1#diff-db66e89c8686cdef7ed55c44cd6b14e0052868ba481585d371f2d5b78c082521)
> INC-1335: Update Application Insights sampling settings

- helm_deploy/values-prod.yaml
Ref: [prison-api#2156](https://github.com/ministryofjustice/prison-api/pull/2156)
> INC-1335: Migrate to `prison-api` in Cloud Platform

- README.md
- async-api.yml
See related [`hmpps-domain-events`' PR](https://github.com/ministryofjustice/hmpps-domain-events/pull/29).
> INC-1335: Document domain messages

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/ClockConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/TimeZoneIdConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/IncentiveReview.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIncentiveReviewService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/SnsService.kt
- src/main/resources/application-localstack.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/SqsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/ManageIncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/PrisonIncentiveLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/SARResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonOffenderEventListenerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIncentiveReviewServiceTest.kt
- src/test/resources/application-test.yml
- src/test/resources/messages/bookingMoved.json
Depends on:
• [cp#28420](https://github.com/ministryofjustice/cloud-platform-environments/pull/28420)
• [cp#28421](https://github.com/ministryofjustice/cloud-platform-environments/pull/28421)
• [cp#28422](https://github.com/ministryofjustice/cloud-platform-environments/pull/28422)
> INC-1377: React to moved booking events
