ministryofjustice/hmpps-incentives-api

- .circleci/config.yml
https://dsdmoj.atlassian.net/browse/INC-545
Required after [I bumped](https://github.com/ministryofjustice/hmpps-incentives-api/pull/66) the hmpps orb to v5.0 and the [security job wasn't able ](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-incentives-api/240/workflows/d56fae5c-7a70-485a-82fe-ae8847383a29)to run due to [this PR](https://github.com/ministryofjustice/hmpps-circleci-orb/pull/116) removing default versions
> INC-545: set executor versions

- .circleci/config.yml
- build.gradle.kts
- gradle.properties
https://dsdmoj.atlassian.net/browse/INC-567
Copied from https://github.com/ministryofjustice/make-recall-decision-api/pull/86
Have already followed [SonarCloud configuration page](https://sonarcloud.io/project/configuration?id=ministryofjustice_hmpps-incentives-api&analysisMode=GitHubCircleCI) and created `SONAR_TOKEN` env variable in CircleCI
> INC-567: enable SonarCloud with code coverage metrics

- .circleci/config.yml
- Dockerfile
- build.gradle.kts
- renovate.json
https://dsdmoj.atlassian.net/browse/INC-633
I raised https://dsdmoj.atlassian.net/browse/INC-634 and https://dsdmoj.atlassian.net/browse/INC-635 to re-enable Veracode and JaCoCo
> INC-633: upgrade to Java 18 and Kotlin 1.7

- README.md
It is possible that publishing an error to SNS locally fails if the
default AWS profile points to a region different than `eu-west-2`
> Improved SNS instructions in README

- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IepLevelService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IepLevelServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
- src/test/resources/messages/prisonerReceivedReasonAdmission.json
- src/test/resources/messages/prisonerReceivedReasonTransferred.json
- src/test/resources/messages/prisonerReleased.json
The domain event contains the date/time of when the even occurred so
we can use this time in the created `PrisonerIepLevel` record instead
of "now" (when the domain event is processed).
Also:
- updated SNS message payload so that datetimes have same format as per production messages (with local time offset)
- simplified `filter {}` expression to get list of active prison levels
> INC-733: Set IEP level review time to when the domain event occurred

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/HmppsIncentivesApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonApiService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
We saw some odd `NoSuchElementException` exceptions when Prison API responded with a `404 Not Found`, this meant these requests to the Incentive API responded with a `500 Internal Server Error`.
A `NoSuchElementException` was caused by [calling `first()` on an empty flow](https://github.com/ministryofjustice/hmpps-incentives-api/blob/88481925a2360cfc8bbdc67bbb423e3338d9364e/src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt#L56).
The `PrisonApiService` methods were swallowing the `NotFound` exceptions and returning an empty flow in those cases causing the `NoSuchElementException` above when calling `.first()` on it.
`PrisonApiService` doesn't swallow exceptions anymore and `NotFound` exceptions are now handled and clients gets a `404 Not …
> INC-735: Avoid 500s when Prison API responds 404

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/BehaviourSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveSummaryResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IepLevelService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveSummaryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- removed unnecessary `coroutineScope`
- simplified `getIncentivesSummaryByLocation()` method
- use `fold()` when counting case notes
- use property references when it makes code a bit more concise
- moved BehaviourSummary classes in `dto` packages for consistency
- removed unnecessary `let {}`/`with()`
> Simplify suspend functions/codebase

- helm_deploy/hmpps-incentives-api/values.yaml
https://dsdmoj.atlassian.net/browse/INC-768
#162 corrected `dlqName` which meant we went into [this block](https://github.com/ministryofjustice/hmpps-spring-boot-sqs/blob/80dc3d244e05f126544819e21d5ed69995ba37d0/hmpps-sqs-spring-boot-autoconfigure/src/main/kotlin/uk/gov/justice/hmpps/sqs/HmppsSqsProperties.kt#L69) and the app threw an exception on startup because `dlqSecretAccessKey` was not configured as [per the docs](https://github.com/ministryofjustice/hmpps-spring-boot-sqs/blob/80dc3d244e05f126544819e21d5ed69995ba37d0/README.md?plain=1#L102)
> INC-768: fix helm DLQ_SECRET_ACCESS_KEY param

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IepSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
Endpoint invoked to synchronise IEP reviews from NOMIS.
As per ticket this endpoint has same request format as per migration endpoint (but it publishes the domain events).
As part of this I've renamed the `IepMigration` data class into `SyncPostRequest`.
> INC-738: POST /iep/sync/booking/{bookingId} endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonerIepLevelRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonerIepLevelRepositoryTest.kt
The `prisoner_iep_level` DB table has `current` boolean column (`current` is something of a legacy concept coming from NOMIS. In theory the record with latest `review_time` should be the "current")
More than one record can currently have that set to `true` which can cause a problem for the following method/generated query that expect only one result:
```
findOneByBookingIdAndCurrentIsTrue()
```
I've changed this method to `findFirstByBookingIdAndCurrentIsTrueOrderByReviewTimeDesc()`:
- so it sorts by `review_time` DESC (as that's the natural order)
- it returns the first record with `current=true`
This should avoid that exception to be raised on transfer.
I've also added ordering to the other repository method:
- renamed `findAllByBookingIdInAndCurrentIsTrue()`
- to …
> INC-824: Fix handling of 'TRANSFERRED' domain event when 2+ current=true

- .trivyignore
- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IepSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveSummaryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/DaysOnLevelTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IepSummaryDateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
• Adds new derived field to `IepSummary` with a very simple calculation for next review date. `lastReviewDate + 1 year` applies to people not on basic, not newly in prison, not recalled and not transferred since last review.
• Fixes some minor test issues
• Changes how `daysSinceReview` is calculated to prevent errors and confusion, see explanation in 273f44ae3c934a62e8a5b69c5758bd75cf608c11
> INC-815: Basic next review date calculation

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IepSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveSummaryService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IepSummaryDateTest.kt
Previously, it silently returned 0 when history was unavailable (i.e. `IepSummary` was loaded "without details") instead of indicating that there was a problem. It was only used in one place (on an intermediate object) and was not serialised as part of the `IepSummary` schema.
Throwing an exception seems prudent to indicate that there is an _implementation_ problem (wrong details passed in). The calculation has also been moved closer to where it's used. It's less error prone than being a method that looked reusable.
> INC-827: Improve `daysOnLevel` calculation

- helm_deploy/hmpps-incentives-api/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/FeatureFlagsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
When a new IEP review is created two things happen to update NOMIS/notify other services that may be interested in this:
1. a domain event is published
2. an HTTP request to Prison API's `POST /api/bookings/{bookingId}/iepLevels` is made
A sync service is being developed/built and it's currently in `dev` environment.
This service is updating NOMIS when the domain event above is published.
This means that in `dev` at the moment a duplicated review is recorded in NOMIS (a record is created by our POST request to Prison API and another is created by the sync service).
A new feature flag (`feature.review-added-sync-mechanism`, env variable `FEATURE_REVIEWADDEDSYNCMECHANISM`) can be set to determine how a new IEP review is propagated to NOMIS/other services:
- when set to `DOMAIN_EVENT` a …
> INC-760: Feature flag to either publish domain event or call Prison API on new IEP review

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/AuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/SnsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
`DELETE /iep/sync/booking/{bookingId}/id/{id}`
- delete an IEP review by id
- publishes a `IEP_REVIEW_DELETED` domain/audit events
- when the deleted IEP review had `current=true`, sets another one (latest) as current so that there is one current IEP review for that `bookingId`
> INC-872: sync DELETE endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/FeatureFlagsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IepSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveSummaryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceForNomisDataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IepSummaryDateTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
Requirements/rules
-------------------
> PF 5.16 Prisoners placed on Basic must be reviewed within 7 days and if
> not suitable to return to Standard level further reviews must be
> undertaken at least every 28 days thereafter
Ticket scope
-------------
Ticket INC-818: https://dsdmoj.atlassian.net/browse/INC-818
There are other rules but this ticket is about improving the next review
date for prisoners on 'Basic' level.
Technical implementation
-------------------------
The `nextReviewDate` property in `IepSummary` has now a getter which
delegates the calculation of the next review date to the `NextReviewDateService`.
The idea is that this service is stateless and given all the information
it needs, determines the next review date.
**NOTE**: At the moment this information is the last …
> INC-818: next review date takes 'Basic' into consideration

- renovate.json
…so that it does not suggest too many unnecessary updates to patch-level versions.
E.g. the HMPPS CircleCI orb is fine being pinned at the minor level because CircleCI will always use the latest patch version then anyway
> Have renovate-bot preserve existing semver ranges

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/HmppsIncentivesApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IepSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveSummaryResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/util/parameterValidators.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceForNomisDataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveSummaryResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/OpenApiDocsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/util/ParameterValidatorTests.kt
Spring's validation of parameters using annotations does not work in suspend functions. C.f. https://github.com/spring-projects/spring-framework/issues/23499
We don't currently have the `Validated` annotation on the REST controllers (resources), meaning validation is disabled, but even with this annotation nothing gets checked.
Deserialisation of string parameters into objects like `Int` or `Sort.Direction` works correctly so there _is_ some validation happening.
> INC-883: Improve request parameter validation

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/OffenderSearch.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/OffenderSearchService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/OffenderSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsServiceTest.kt
…which will be needed for future "date of next review" calculations.
Also, changes to use system token to access offender search: Essentially, we only require the `MAINTAIN_IEP` role, and this makes sense for the data we actually return to the caller. But to calculate next review dates, we need to load more information on the given offender and the calling user may not have the roles to do so.
> INC-816: Wire up offender search service to return a single offender by prisoner number

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveSummaryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/OffenderSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceForNomisDataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
The rule to determine the next review date _for prisoners on 'Basic'_ is slightly different for prisoners at risk of self harm (have an ACCT alert active and not expired, aka is a prisoner "with open ACCT") their next review date is earlier.
When someone was on 'Basic' and they couldn't move up to an higher level (e.g. they were confirmed on 'Basic' level) the next review would normally be after 28 days. However for prisoners with an open ACCT in this case it would be after 14 days instead.
> PF 5.16 _Prisoners placed on Basic_ must be reviewed within 7 days and if not suitable to return to Standard level further reviews must be undertaken at least every 28 days thereafter
>
> _Exception for those identified as at Risk of Suicide and Self-harm (ACCT)_ and for young people, where further …
> INC-852: Take open ACCT status when determining next review date

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateServiceTest.kt
> [...] if not suitable to return to Standard level further reviews must
> be undertaken at least every 28 days thereafter.
>
> Exception for those identified as at Risk of Suicide and Self-harm (ACCT)
> and for young people, where further reviews must be undertaken at least
> every 14 days thereafter
This change adds this exception for "young people" to the 'Basic' rule.
> INC-896: Added "young people" exception for next review when on Basic

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IepSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/ReviewType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/PrisonerIepLevel.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveSummaryService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IsRealReviewTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveSummaryMasteredResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
If reviews come from our database they'll have a `reviewType`.
- if this is `REVIEW` they're real reviews
- if this is `MIGRATED` these were migrated from NOMIS and we assume they're
"real"
- when the data is coming from Prison API/NOMIS (as it currently does
for the time being in production) we don't have the review type information
and we cannot discriminate but we consider them real reviews as in the case of `reviewType='MIGRATED'`
(ultimately this will not matter as we'll only get data from our DB and
these "legacy" reviews will have 'MIGRATED' type)
> INC-820: Next review date calculation only takes in consideration real reviews

- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IsRealReviewTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/helper/JwtAuthHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/SqsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/health/HealthCheckTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/OffenderSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveSummaryMasteredResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveSummaryResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/OpenApiDocsTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonOffenderEventListenerTest.kt
Mostly: `internal` visibility modifier is effectively "public" because this only contains one module, so it might as well be removed or replaced with something more private.
Minor tidy-up: removal of unnecessary suppressions, import fix, more consistent use of object mappers in tests.
> INC-903: Tidy up code

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
`assignedLivingUnitId` can be 0 which is not a location that can be looked up in prison-api (cf. `GET /api/bookings/{bookingId}`)
> INC-921: Fix situation during migration where assigned living unit is not known

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/HmppsIncentivesApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/NextReviewDate.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/NextReviewDateRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonerIepLevelRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateGetterService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateUpdaterService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/adapters.kt
- src/main/resources/db/migration/V1_18__next_review_date.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/OffenderSearchMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/NextReviewDateRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonerIepLevelRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceForNomisDataTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateGetterServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateUpdaterServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/testData.kt
- creates `next_review_date` database table with `booking_id`/`next_review_date` columns
- mechanism to update next review date for one/multiple prisoners
- mechanism to get next review date for one/multiple prisoners
- this tries to get them from the database first
- update these in the database if missing
- return the next review dates
- create a new review triggers the update of the next review date in the database
- this includes admissions, transfers, merges, etc...
> INC-817: Store next review date in the database

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
Some of these endpoints requests may trigger the update of several records in the DB so it makes sense for these operation to be atomic/transactional.
NOTE: This is part of ongoing support for syncronisation testing
> INC-813: Made sync endpoints transactional

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
The use of `.let {}` instead of a simple `if ()` caused the the sync DELETE endpoint to always try to set another review as current even when unnecessary.
This can lead to a violation of the DB constrain that prevents more than one current reviews for the same `bookindId`.
See: https://mojdt.slack.com/archives/C03BCRW4B5G/p1668786899831079
> INC-930: Fix sync DELETE endpoint always assuming review was current

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/SnsService.kt
- src/main/resources/application-localstack.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonOffenderEventListenerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
- src/test/resources/application-test.yml
- src/test/resources/messages/prisonerUpdated.json
- When a prisoner is updated and if the alerts changed update the next review date (see below)
- Fix incentives' reviews domain events description always being "An IEP review has been added", even tho maybe a review was actually patched or deleted (although admittedly these should happen less frequently)
- Better names for methods
**NOTE**: This is the processing side of the ticket, we need to [update the CP terraform resource](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-domain-events-dev/resources/hmpps-incentives.tf#L118) to also get `prisoner-offender-search.prisoner.updated` domain events.
Currently based on `prisoner-offender-search.prisoner.updated` event (`Domain` topic).
This event is …
> INC-901: Update next review date on alerts changes

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/util/pagination.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/util/PaginationTests.kt
Notable change: the reviews resource now counts pages starting from 0 (not 1 as before) to match Spring Data’s conventions; other HMPPS apis do this too.
> INC-931: Paginate responses of incentives reviews

- src/main/resources/db/migration/V1_20__prisoner_iep_level_add_index_on_booking_id.sql
Some of the queries getting the reviews for a prisoner are slow, add an index on `booking_id` should help avoid a full table scan for these.
(to the `prisoner_iep_level` DB table)
> INC-813: Add index on reviews' `booking_id`

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/NextReviewDate.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateUpdaterService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateUpdaterServiceTest.kt
`@LastModifiedDate` annotation doesn't work. It's probably because we're not using spring-data-jpa and instead we use `spring-data-r2dbc`.
Only place which updates `NextReviewDate` records is the `NextReviewDateUpdaterService` so we can explicitly set the `whenUpdated` field to now when this happens.
Tests had to be updated in order for some mocks to work as expected but overall this is simple enough and it works.
> INC-936: manually set whenUpdated in NextReviewDate records

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/NextReviewDate.kt
We noticed that `@CreatedDate`/`@LastModifiedDate` annotations don't work because we're using `spring-data-r2dbc` (and not `spring-data-jpa`).
The `when_created` column is populated correctly because of the DB default, but it makes sense to remove this annotation to avoid confusion.
> Remove unnecessary/broken `@CreatedDate` annotation

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
During the migration a lot of intermediate reviews are created. It doesn't make much sense to update the next review date every time a potentially old review is created.
This has also 2 performance benefits:
- we avoid making more requests when handling migration requests which makes the migration faster
- when we'll publish domain events on next review date change these will trigger a reindex of the prisoner in ES/Offender Search API: we don't want to trigger a reindex for each of the intermediate/old reviews being migrated from NOMIS
> INC-949: Migration endpoint don't update next review date

- src/main/resources/application.yml
…because 1s is short enough for some tests to be flakey. Additionally, 1s might be a bit too short for external apis for the deployed app too: a dependency experiencing high load would reply slower and cause our app’s health check to be flappy.
Sample flakey health-check response from `Health page reports ok` test:
```json
{
"status": "DOWN",
"components": {
"audit-health": {
"status": "UP",
"details": {
"queueName": "45c4180c-facf-4b06-b77c-f4c1dfefe98d",
"messagesOnQueue": "0",
"messagesInFlight": "0"
}
},
"authHealthCheck": {
"status": "DOWN",
"details": {
"error": "java.lang.IllegalStateException: Timeout on blocking read for 1000000000 NANOSECONDS"
}
},
"diskSpace": {
"status": "UP",
"details": {
"total": 250790436864,
"free": 29556772864,
"threshold": 10485760,
"exists": true
}
}, …
```
> INC-940: Increase health-check timeout for external apis to 3s

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/SnsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
Because of the timing between when the sync service tells us about new reviews (via `POST /iep/sync/booking/:bookingId` endpoint) and when we respond/this is stored in the sync mapping service, another domain event is published causing duplicated reviews in NOMIS.
The sync service should really ignore domain events published by this sync POST endpoint because these reviews are already in NOMIS.
We're now adding a `"reason": "USER_CREATED_NOMIS"` (in the usual `additionalInformation`) so that sync service can ignore these domain events and avoid duplicates.
> INC-962: Fix for sync race condition/duplicated NOMIS reviews

- helm_deploy/hmpps-incentives-api/values.yaml
The environment variable was renamed in most places but not in the default values leading to the pod having both environment variables set but with different values. I don't know which one would win and it's best to avoid confusion anyway.
See Pod variables in `dev`:
```YAML
- name: FEATURE_REVIEWADDEDSYNCMECHANISM
value: PRISON_API
- name: FEATURE_REVIEW_ADDED_SYNC_MECHANISM
value: DOMAIN_EVENT
```
(which one will Spring Boot use?)
> INC-961: Fix default value for sync mechanism after rename

- src/main/resources/db/migration/V1_22__prisoner_iep_level_increase_location_id_length.sql
Some of the SQL INSERT rarely fails because of the fact a location description is longer (up to 240 characters) than the `location_id` column where they're stored (which is currently 30 characters max).
Given we're storing the location description, and as also suggested by Syscon, I'm increasing the length of this column to 240 characters so that it's in line with the maximum possible value.
> INC-966: Increase `prisoner_iep_level.location_id` column length

- helm_deploy/values-prod.yaml
When getting the history of reviews for a prisoner use the Incentives DB instead of getting it from NOMIS (via Prison API)
NOTE: We can now do this because we migrated all the data and 2-way syncing is enabled.
> Use Incentives database as source of truth

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/prisonapi/prisonapidto.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonOffenderEventListener.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/SnsService.kt
- src/main/resources/application-localstack.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/service/PrisonOffenderEventListenerIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonOffenderEventListenerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
- src/test/resources/application-test.yml
- src/test/resources/messages/prisonerAlertsUpdated.json
Before this we were listening to the `prisoner.updated` domain event and updating the next review date any time any alerts changed. This is not ideal as we receive a lot of events we don't care about and also we potentially re-calculate the next review date when non-ACCT alerts changed.
Since then Andy has added a more specific domain event published when alerts changes (`prisoner-offender-search.prisoner.alerts-updated`), this domain event should be less frequent and it also includes the alert codes of the alerts added/removed meaning we can update the next review date only when an ACCT alert was added/removed.
**NOTE**: The old domain events are no longer processed so this can only be merged once the wiring to subscribe to the new events is working. The CP terraform changes were merged …
> INC-958: Use new `alerts-updated` domain events to recalculate the next review date

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/ReviewType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/main/resources/db/migration/V1_22__prisoner_iep_level_alter_review_type_length.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewServiceTest.kt
When someone is re-admitted into prison with the same booking (e.g. because of a recall, remand or potentially other similar cases) a "review" is created with time "READMISSION".
The next review date service checks if the last "review" is a readmission and in that case uses the same rules used for new prisoners to calculate the next review date (so within 3 months from readmission date for adults, within 1 month for young people).
**NOTE**: The Incentives policy only mention recalls but we don't have any reliable way to discriminate between recalls and other kind of readmissions. We think it's OK to treat all readmissions as new prisoners (for the purpose of calculating the next review date) but I'll also check with Steve.
> INC-821: Next review date calculation takes readmissions in consideration

- renovate.json
This reverts commit 5801f64f314b2c9347e6a8023ea3149385579f87.
Should resolve https://github.com/ministryofjustice/hmpps-incentives-api/issues/312
> Revert "Tweak Renovate to pin JDK version in Docker (#310)"

- docker-compose-local.yml
- docker-compose.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveSummaryService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveSummaryMasteredResourceTest.kt
Where a prisoner has just entered prison (since migrating to new service 5 December) - if no REAL review has taken place the prisoner is show in a “Invalid” tab on the review screen.
Change this to put them in a “**No review**” tab, so its clear that no “real review” has yet taken place.
> INC-1010 Issue with Invalid type in Prisoners in Incentives Review screen (old version)

- helm_deploy/hmpps-incentives-api/Chart.yaml
I made changes with https://github.com/ministryofjustice/hmpps-helm-charts/pull/86
Tested locally by following the steps here https://github.com/ministryofjustice/hmpps-helm-charts#testing-changes-locally also want to check it deploys to dev without issues
> Bump generic-service to double-check latest version hasn't broken anything

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IepLevelService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonApiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/util/CachedValue.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IepLevelServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/util/CachedValueTest.kt
We discovered that quite often getting the global list of all the incentive levels can take several seconds (often taking 30-60 seconds, [see AppInsights query](https://portal.azure.com#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa5ddf257-3b21-4ba9-a28c-ab30f751b383%2FresourceGroups%2Fnomisapi-prod-rg%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2Fnomisapi-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0VOuwqDMBTd%252FYqLu8Slo91CKUgpUrpKmhwxoDchV1sK%252Ffimg3Y6cN4OEezA1kOKD71GJJBbk1l8YDrSoa7rnbdTWF3fhQkXM4OahspxjlEqzxa8%252BCekMtGXe4A320nfSGVJJQxZyPbKhdl4FrXhWV%252F7Vt91q2xwkLJQirYeWa2FyK9qMJMgD0hICz3e%252F685Y79cWyJgzgAAAA%253D%253D/timespan/PT4H))
It's not clear why this endpoint …
> INC-988: Cache global list of all incentive levels

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IncentiveReview.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsServiceTest.kt
In order for the UI/'Reviews' table to show:
- Number of prisoners overdue at each level ("dashboard" to be shown above the Reviews table)
- Number of prisoners at each level (to be shown in parenthesis in the tabs)
This is an example of the field added to the response:
```JSON
{
"levels": [
{
"levelCode": "BAS",
"levelName": "Basic",
"reviewCount": 1,
"overdueCount": 0
},
{
"levelCode": "STD",
"levelName": "Standard",
"reviewCount": 3,
"overdueCount": 0
},
{
"levelCode": "ENH",
"levelName": "Enhanced",
"reviewCount": 1,
"overdueCount": 1
}
],
// [...]
}
```
The response now contains the list of Incentive levels for the given prison.
This means the UI doesn't need to make this additional HTTP request.
We're also deprecating these 2 fields:
- `overdueCount`, that's the total number of …
> INC-1074: Add counts by level to reviews endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IncentiveReview.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsServiceTest.kt
⚠️ **DO NOT** merge/deploy this PR until the UI change is promoted to `preprod`/`prod`.
These two fields will soon no longer be used by the UI once this PR is promoted to `preprod`/`prod`:
https://github.com/ministryofjustice/hmpps-incentives-ui/pull/392
This is an "internal" API only used by the `incentives-api`, [see Azure `dependencies` query](https://portal.azure.com#@747381f4-e81f-4a43-bf68-ced6a1e14edf/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa5ddf257-3b21-4ba9-a28c-ab30f751b383%2FresourceGroups%2Fnomisapi-prod-rg%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fnomisapi-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA2WOsQ7CIBiE9z4FYS88QUfj5mDcmwYu7V9bIPxAFx%252FeotE0Ot1w%252Bb47iwBn4QyBm4fYJkSINMQRSXSdkOQMXKICbod …
> INC-1074: Remove deprecated `reviewCount`/`overdueCount` in Reviews endpoint

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateServiceTest.kt
Previous logic was very simple and only checked the last incentive record of a prisoner to determine if it was a readmission.
This doesn't work if the prisoner is transferred before they got reviewed.
The new logic is similar but it allows for newer non-review entries present after the readmission one.
Example:
- `TRANSFER`
- `TRANSFER`
- `READMISSION`
- [...]
The two entries of type `TRANSFER` here are "ignored" (as they're not real reviews). Readmissions are also not real reviews but they're considered when determining whether the prisoner has been readmitted but hasn't been reviewed yet.
The date of the readmission entry is used as a starting date for the calculation of the next review date as expected (+3 months in general but +1 month for young people).
> INC-1069: Improve next review date logic for readmissions

- helm_deploy/values-preprod.yaml
Same as https://github.com/ministryofjustice/hmpps-incentives-api/pull/366 & https://github.com/ministryofjustice/hmpps-incentives-api/pull/369
> INC-1119: use new HMPPS Domain Events queue from the Incentives namespace - PreProd

- Dockerfile
I noticed in AppInsights the `application_Version` was `${BUILD_NUMBER}`, so checked other services and the Kotlin Template (https://github.com/ministryofjustice/hmpps-template-kotlin/blob/fe470fa32d8c162981a873976928dfedb42d004d/Dockerfile#L13-L14)
> Include BUILD_NUMBER in the run stage of Dockerfile

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/PrisonIncentiveLevel.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonIncentiveLevelService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonIncentiveLevelRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResourceTest.kt
This does not add any validation/ranges to spending limits; simply sets the fallback values for any newly-created incentive level information for a prison in cases where an incomplete payload is submitted.
> INC-1143: Use sensible spend limit defaults from PSI

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/AuditService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveLevelService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonIncentiveLevelService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResourceTest.kt
Submit SQS messages when an `IncentiveLevel` or `PrisonIncentiveLevel` is modified.
NB: For now, this happens inside transactions so data will not be committed to database at the point the message is received somewhere. This shouldn't hugely matter in case of audit events, but "HMPPS domain events" will need to be outside transactions so suggest moving the audit submissions too at that point.
> INC-1148: Audit changes to incentive levels and their per-prison information

- helm_deploy/values-preprod.yaml
This environment is hardly used and does not warrant 4 pods running at all times.
> Scale `preprod` replicas from 4 to 2

- doc/architecture/decisions/0004-reference-data-sync.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IncentiveLevel.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/IncentiveLevel.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonIncentiveLevelRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveLevelService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonIncentiveLevelService.kt
- src/main/resources/db/migration/V1_28__required_incentive_levels.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/IncentiveLevelResourceTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/IncentiveLevelRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonIncentiveLevelRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/PrisonIncentiveLevelResourceTest.kt
New business rules:
• If an incentive level is globally required, per-prison levels and associated information cannot be deactivated
• If an incentive level becomes globally required, it will be activated automatically in all prisons that currently have some active levels (essentially, in all active prisons); associated information will use policy defaults
> INC-1171: Allow globally-defined incentive levels to require per-prison information to be active

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/PrisonIncentiveLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/SnsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/IncentiveLevelResourceTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/SqsIntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/PrisonIncentiveLevelResourceTest.kt
When incentive levels or per-prison associated data is modified, HMPPS domain events are sent using SNS. Now tests assert that this happens at appropriately. This ensures that changes in #395 are correctly implemented.
Also might as well document the api endpoints more thoroughly.
> INC-1188: Test domain events are raised when incentive levels are modified

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IncentiveLevel.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/PrisonerIepLevel.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/Adapters.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateUpdaterService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateUpdaterServiceTest.kt
The `IepDetail` class is still used, and in fact even part of the public interface
of some of the endpoints. However is kinda a legacy data class.
The `NextReviewDateService` now uses `PrisonerIepLevel` values which is
what's stored in the database. This is the new representation of an incentive
record.
> `NextReviewDateService` no longer uses `IepDetail`

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IncentiveLevel.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/IncentiveLevel.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveLevelService.kt
- src/main/resources/db/migration/V1_31__incentive_level_add_description_column.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResourceTest.kt
This field can contain a human description of an Incentive level but it can be an empty string (it's not nullable in the DB tho)
> INC-1193: Add `description` field to Incentive levels

- doc/architecture/decisions/0002-incentive-api-architecture.md
- doc/architecture/decisions/0004-reference-data-sync.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IepSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateUpdaterService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIepLevelReviewService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateUpdaterServiceTest.kt
While working on removing the migration/sync endpoint I've came across a few small things that can be sorted/merged before that PR:
- unused params
- `NextReviewDateUpdaterService` no longer uses the `IncentiveLevelService`
- `useClientCredentials` is no longer used in `getPrisonerIepLevelHistory()` (because Incentive records now come from our database, not a Prison API call)
- typos, spelling mistakes etc
- added a comment about `daysSinceReview` to warn IntelliJ is wrong and it's actually used.
> Tidying up

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelsResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepReviewsResource.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepLevelsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepReviewsResourceTest.kt
The old `IepLevelResource` class contained endpoints to manage Incentive records (`/iep/reviews/*`) but also an endpoint to get the list of Incentive levels for a given prison (`GET /iep/levels/{prisonId}`).
I've moved the latter in its own `IepLevelsResource` updating the Swagger name to reflect this and renamed the existing resource class to `IepReviewsResource`.
Relevant tests were also moved or removed to the correct test file.
**NOTE**: The API didn't change, the endpoints are working as before, this is an internal refactoring for clarity.
Also note that the `GET /iep/levels/{prisonId}` and corresponding resource will probably be deprecated and removed in favour of the new `/incentives/` endpoints once we migrated the reference data off NOMIS.
> `/iep/` resources tidy up

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonIncentiveLevelRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveLevelService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonIncentiveLevelService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/WebClientUtil.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonIncentiveLevelRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResourceTest.kt
To be allowed to deactivate a level globally, it must not be active in any prison
> INC-1202: Restrict global incentive level deactivation

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonIncentiveLevelService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/PrisonIncentiveLevelResourceTest.kt
It doesn't make sense for a level to be active in a prison when it's inactive globally. This particularly stopped making sense after part 1 of INC-1202 (#415) where a level could not be globally deactivated if it was active in some prison.
> INC-1202: Restrict activating a level in a prison if it is not globally active

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonerIepLevelRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/CountPrisonersService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonIncentiveLevelService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonerIepLevelRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/CountPrisonersServiceTest.kt
Knowing the _number_ of prisoners on a level is not necessary so SQL and offender search calls can be made simpler.
Tweaks #417
> INC-1202: Check if some prisoner exists on a level in a prison

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/HmppsIncentivesApiExceptionHandler.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IepReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/PrisonIncentiveLevelResourceTest.kt
NOTE: There is no "bubbling up" of exceptions problem AFAICT, the  `ServerWebInputException` is thrown automatically by Spring (when the request format is incorrect) and this is happening before any of our code (e.g. resource method) could be reached, therefore we don't have much control over this (but also it doesn't matter as the user gets a `400 Bad Request` anyway)
- improved handler for `ServerWebInputException`
- document what's covering
- response's user message is simpler and explain what could have been wrong in the request (before this could contain something like `Failed to read HTTP message` which is misleading and almost sound like a networking problem)
- response's developer message and log includes the exception cause which contains useful information about what caused the …
> INC-1199: Tweak to exception handling

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/HmppsIncentivesApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonIncentiveLevelRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveLevelService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonIncentiveLevelService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/helper/ErrorResponseHelper.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonerIepLevelRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/PrisonIncentiveLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/util/ErrorCodeTest.kt
Error responses could always have contained an integer `errorCode` but it was not used in practice. For clients of the api to be able to _precisely_ know the error that occurred, it's better to use an enum / constant code rather than rely on text included in the message.
Similarly, the `moreInfo` field hasn't been used yet: Trying to remove an incentive level globally will now return an error with prisons that currently have it active.
Depends on (and won't merge with) #425
> INC-1202: Return better error responses when incentive levels cannot be modified

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/IncentiveLevel.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResource.kt
The database already had a hard limit of 30 characters, but the modification endpoints would have previously returned a generic 500 server error instead of a meaningful response.
> Improve error messaging and documentation regarding incentive level name length

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonIncentiveLevelRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonIncentiveLevelService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/jpa/repository/PrisonIncentiveLevelRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveLevelResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/PrisonIncentiveLevelResourceTest.kt
Previously, only the level that was being directly edited had events published for the change. Now, if another level becomes non-default-for-admissions, it will also publish audit events.
> INC-1234: Send audit events for other levels changed when one becomes the new default

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonIncentiveLevelService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/PrisonIncentiveLevelResourceTest.kt
When a prison is closed, it's prison incentive levels should be deactivated. This tests the situation where the same prison is later reopened.
NB: the first level that is activated must be a default according to business rules, but furthermore it must also have been the level that was _previously_ the default.
If a prison had these levels:
• BAS active
• STD active
• ENH active and default
and is closed, then it ends up with:
• BAS inactive
• STD inactive
• ENH inactive and default
To reactivate the whole prison the actions needed are:
1) activate ENH resulting in 
• BAS inactive
• STD inactive
• ENH active and default
2) activate all other required levels (BAS & STD) resulting in 
• BAS active
• STD active
• ENH active and default
only _then_ can the default level be changed if …
> INC-1269: Increase test coverage for the case of a prison being re-activated

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/PrisonIncentiveLevelResource.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonIncentiveLevelService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/PrisonIncentiveLevelResourceTest.kt
This is useful when setting up a new prison. If in future there are domain events raised when a prison is created, incentives-api could listen for them and automatically set up the prison.
It can also be used to ensure that a prison has the required set of levels active and that Standard is the default for admission.
> INC-1276: Add api endpoint to reset levels in a prison

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/util/ErrorCodeTest.kt
We want to be able to look up reviews for a given location by using a prefix like "MDI-1-" (including a trailing hyphen) so that other locations aren't accidentally included. Using a prefix of "MDI-1" (no trailing hyphen) would also match locations starting with "MDI-10" and that's wrong.
However, when looking up the details of a location in prison-api, trailing hyphens will not be valid so need to be removed.
> Fix location lookup when retrieving reviews

- buildSrc/src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/PortForwardTask.kt
Using the real port could lead to "accidents". For example if the gradle task to connect the preprod/prod DB is left running and tests are run at the same time they may potentially run against a non-test database which can cause all sort of problem (especially if the test then truncate the table)
It's better to err on the side of caution and use a non-standard port (`12345`) by default. This can be changed anyway for whatever reason.
> Use non-standard ports when using port forward tools

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
Enable 'scheduled downtime' feature of generic-service helm chart: https://github.com/ministryofjustice/hmpps-helm-charts/tree/main/charts/generic-service#scheduled-downtime
> To enable this feature, you first need to add a `scheduled-downtime-serviceaccount`
> Service Account to your namespace, with permissions to scale your deployment.
The required kubernetes `ServiceAccount` is already there:
- `dev`: https://github.com/ministryofjustice/cloud-platform-environments/blob/b534875bb2347de40543ceabc3d5ce102b6514fd/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-incentives-dev/resources/scheduled-downtime.tf
- `preprod`: https://github.com/ministryofjustice/cloud-platform-environments/blob/b534875bb2347de40543ceabc3d5ce102b6514fd/namespaces/live.cloud-platform.service.justice.gov …
> INC-1235: Stop non-prod instances during non-working hours

- .circleci/config.yml
- helm_deploy/hmpps-incentives-api/values.yaml
… keeping `dev` unrestricted.
Don’t merge until [ui#649](https://github.com/ministryofjustice/hmpps-incentives-ui/pull/649) is tested.
> Move `prod` and `preprod` to use the same shared IP address allow lists

- helm_deploy/hmpps-incentives-api/values.yaml
Ref: [hmpps-ip-allowlists#2](https://github.com/ministryofjustice/hmpps-ip-allowlists/pull/2)
> Remove health-kick from allow list since it is now within Cloud Platform

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/KpiService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NextReviewDateUpdaterService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/task/UpdateKpis.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/KpiServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/task/UpdateKpisTest.kt
Ref: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/run-blocking.html
`runBlocking` blocks the current thread, but since coroutines share a small pool of threads (perhaps even 1 thread??) it means that this one cannot be used to progress any other coroutines. This could feasibly lead to a deadlock or, at the very least, defeats the purpose of coroutines.
> Avoid calling `runBlocking` from within coroutines as recommended in documentation

- src/main/resources/application-localstack.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/IncentiveLevelResourceTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/SqsIntegrationTestBase.kt
- src/test/resources/application-test.yml
This update changes hard-coded queue names and ARNs in YAML files to generated UUIDs, improving flexibility for testing and development. Furthermore, the complexity of tests in IncentiveLevelResourceTestBase has been reduced by removing extra setup steps for domain events subscription, thanks to adding "test" queue in the SqsIntegrationTestBase and the application-test.yml files.
> INC-1356 Update UUID for queue names and simplify queue tests

- helm_deploy/hmpps-incentives-api/values.yaml
The nginx ingress annotation in the helm_deploy/hmpps-incentives-api/values.yaml file has been updated. The previous 'configuration-snippet' key has been replaced with 'server-snippet', reflecting a change in the server tokens and access denial settings for specific locations.
> INC-1356 Update nginx ingress annotation in helm values.yaml

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/HmppsIncentivesApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/SubjectAccessRequestService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/SARResourceTest.kt
When no Incentive reviews are found, or match the given date range, this endpoint not responds `204 No Content` instead of `404 Not Found` or `200 OK` with empty content (respectively)
> INC-1364: SAR endpoint responds `204 Not Found` if no reviews

- .circleci/config.yml
Ref [hmpps-template-kotlin#209](https://github.com/ministryofjustice/hmpps-template-kotlin/pull/209)
> INC-1335: Use same version of java for Veracode scanning as required by HMPPS plugins

- docker-compose.yml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- locations-inside-prison-data/mappings/health.json
- locations-inside-prison-data/mappings/location-MDI-1.json
- locations-inside-prison-data/mappings/location-not-found.json
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/prisonapi/PrisonAPI.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/health/HealthPingCheck.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/LocationsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonApiService.kt
- src/main/resources/application-dev.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/health/HealthCheckTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/LocationsMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/resource/IncentiveReviewsResourceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/IncentiveReviewsServiceTest.kt
- src/test/resources/application-test.yml
⚠️ ~This PR is on a branch off [this other one](https://github.com/ministryofjustice/hmpps-incentives-api/pull/596)~ ⚠️  
The [reviews endpoint](https://incentives-api-dev.hmpps.service.justice.gov.uk/webjars/swagger-ui/index.html?configUrl=/v3/api-docs#/Incentive%20review%20summary/getReviews)'s response has a `locationDescription` field with the human description of a location (e.g. Houseblock 1). This is displayed in the UI reviews table page (this endpoint is "internal" and used only by the UI).
Before this PR this description was populated using the now deprecated `GET /api/locations/code/{locationId}` in Prison API endpoint.
The service now makes a request to the new Locations Inside Prison API. Specifically it uses the [`GET /locations/key/{key}` …
> INC-1371 (part 2): Get location description from Locations API

- Dockerfile
…since gradle now complains about not finding the right toolchain
> INC-1335: Build application using JDK (not JRE) base image

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
Send alerts to our Slack dev channel (`#incentives_dev`) instead of `#dps_alers`/`#dps_alerts_non_prod`.
> INC-1335: Send alerts to dev channel

- helm_deploy/hmpps-incentives-api/values.yaml
…the k8s secret itself is created by terraform from a shared DPS secret in a AWS systems manager parameter
Ref: [hmpps-template-kotlin#254](https://github.com/ministryofjustice/hmpps-template-kotlin/pull/254)
> INC-1335: Get Azure Application Insights settings from kubernetes secret directly

- renovate.json
From Renovate perspective this is the whole `group:name`, e.g. `"io.swagger.parser.v3:swagger-parser"`.
> Fixed "matchPackageNames" to include whole package name

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/ClientCachingOAuth2AuthorizedClientService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/OAuth2ClientConfiguration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/integration/wiremock/HmppsAuthMockServer.kt
Improves the management of authorized clients by introducing a caching mechanism. This enhancement aims to optimize performance and reduce unnecessary duplication when handling OAuth2 client operations.
> INC-1398 Add OAuth2 client caching mechanism and configuration to optimize authorized client management.

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/dto/PrisonIncentiveLevel.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/NearestPrisonIncentiveLevelService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/service/PrisonerIncentiveReviewService.kt
All prisons should have a default Incentive level, and when this is not the case this is a misconfiguration and needs to be corrected.
It is an exceptional situation and indeed not being able to determine the default Incentive level throws an exception.
Unfortunately the exception message says doesn't tell **which** prison is causing this exception. This makes the error message more useful so that we can investigate these sort of things, tweaked message:
```
No default level for new admissions (prisonId = '$prisonId')")
```
> More useful logging when no default level for a prison

- src/main/kotlin/uk/gov/justice/digital/hmpps/incentivesapi/config/ClientCachingOAuth2AuthorizedClientService.kt
This pull request standardizes the system username used in OAuth2 client removal, simplifying the process and ensuring consistency.
> INC-1398 Simplify OAuth2 client removal by standardizing to system username.
